version: "3"
services:
  to-api:
    image: node:latest
    volumes:
      - ./test-objects-api/:/app/
    working_dir: /app/
    command: npm start
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"